### ISSUE TITLE
Parent Model variables 

### ISSUE THREAD

**Issue by Joel-Haeberli** [Emaro/Liberica#2]
Hey Dave 

Ich brauche folgende Variablennamen im Super-Model (Kannst sie 1 zu 1 so kopieren):

    private $selectSelectors = array();
    private $selectConditions = array();
    private $updateSelectors = array();
    private $updateConditions = array();
    private $updateValues = array();
    private $deleteId = -1;
    private $setDeleteBy = "";
    private $insertSelectors = array();
    private $insertValues = array();

Zudem sollte das Model und alle seine Untermodels folgende interfaces implementieren:
    
    implements Insertable,
    implements Updateable,
    implements Selectable,
    implements Deleteable

Merci ;)

**Comment by david-schor** [comment]
Wurde erledigt;)
