### ISSUE TITLE
Login Fatal Error

### ISSUE THREAD

**Issue by david-schor** [Emaro/Liberica#26]
If one logs in with wrong login data, there is a fatal error.

    `Fatal error: Uncaught Error: Call to a member function getEmail() on null in C:\xampp\htdocs\Liberica\mvc\model\User.php:218 Stack trace: #0 C:\xampp\htdocs\Liberica\mvc\model\User.php(49): User::userExist('asdaa') #1 C:\xampp\htdocs\Liberica\mvc\Controller\commands.php(20): User::verifyUser('asdaa', 'asd') #2 C:\xampp\htdocs\Liberica\mvc\Controller\Controller.php(39): Xlogin() #3 C:\xampp\htdocs\Liberica\mvc\Controller\Controller.php(26): Controller->run(Array) #4 C:\xampp\htdocs\Liberica\index.php(16): Controller->__construct('login') #5 {main} thrown in C:\xampp\htdocs\Liberica\mvc\model\User.php on line 218`

**Comment by Emaro** [comment]
Closed
